/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBlockhashStorage,
  IBlockhashStorageInterface,
} from "../IBlockhashStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "getBlockHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "blockHash",
        type: "bytes32",
      },
    ],
    name: "setBlockHash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlockhashStorage__factory {
  static readonly abi = _abi;
  static createInterface(): IBlockhashStorageInterface {
    return new utils.Interface(_abi) as IBlockhashStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBlockhashStorage {
    return new Contract(address, _abi, signerOrProvider) as IBlockhashStorage;
  }
}
