/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITrustedOracle,
  ITrustedOracleInterface,
} from "../ITrustedOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "getBlockHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITrustedOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ITrustedOracleInterface {
    return new utils.Interface(_abi) as ITrustedOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITrustedOracle {
    return new Contract(address, _abi, signerOrProvider) as ITrustedOracle;
  }
}
