/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TrustedOracle } from "./TrustedOracle";
export * as factories from "./factories";
export { TrustedOracle__factory } from "./factories/TrustedOracle__factory";
